### ISSUE TITLE
Does not compile for all configurations

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/dynamic-situational-awareness-qt#352]
When compiling on Windows using the release configuration I receive the following error:

`error: dependent '..\..\..\..\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\include\CoordinateConversion\CoordinateConversionController.h' does not exist.`

The debug configuration works fine.

**Comment by JamesMBallard** [comment]
Hi @gisfromscratch.

If only the release configuration fails, you may need to clean your build area. As long as you have the [main branch](https://github.com/Esri/dynamic-situational-awareness-qt/tree/main) for DSA and the [master branch](https://github.com/Esri/arcgis-runtime-toolkit-qt/tree/master) of the toolkit, everything should be working.

Try deleting your shadow build folders and run qmake from scratch to configure the build. Let us know if that works.

**Comment by gisfromscratch** [comment]
Cleaned and rebuild both configurations with no luck.

**DEBUG succeeded:**
`22:54:32: Running steps for project DSA...
22:54:32: Configuration unchanged, skipping qmake step.
22:54:32: Starting: "C:\bin\Qt\Tools\QtCreator\bin\jom.exe" 
	cd arcgis-runtime-toolkit-qt\Plugin\CppApi\ && ( if not exist Makefile.ArcGISRuntimeToolkit_StaticLib C:\bin\Qt\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile.ArcGISRuntimeToolkit_StaticLib D:\LocalGit\Repos\Esri\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\ArcGISRuntimeToolkit_StaticLib.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib
	C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib.Debug
	cd Handheld\ && ( if not exist Makefile C:\bin\Qt\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile D:\LocalGit\Repos\Esri\dynamic-situational-awareness-qt\Handheld\Handheld.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cd Vehicle\ && ( if not exist Makefile C:\bin\Qt\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile D:\LocalGit\Repos\Esri\dynamic-situational-awareness-qt\Vehicle\Vehicle.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cd MessageSimulator\ && ( if not exist Makefile C:\bin\Qt\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile D:\LocalGit\Repos\Esri\dynamic-situational-awareness-qt\MessageSimulator\MessageSimulator.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
22:54:35: The process "C:\bin\Qt\Tools\QtCreator\bin\jom.exe" exited normally.
22:54:35: Elapsed time: 00:02.`

**RELEASE failed:**
`22:52:43: Running steps for project DSA...
22:52:43: Configuration unchanged, skipping qmake step.
22:52:43: Starting: "C:\bin\Qt\Tools\QtCreator\bin\jom.exe" 
	cd arcgis-runtime-toolkit-qt\Plugin\CppApi\ && ( if not exist Makefile.ArcGISRuntimeToolkit_StaticLib C:\bin\Qt\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile.ArcGISRuntimeToolkit_StaticLib D:\LocalGit\Repos\Esri\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\ArcGISRuntimeToolkit_StaticLib.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib
	C:\bin\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib.Release
Error: dependent '..\..\..\..\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\include\CoordinateConversion\CoordinateConversionController.h' does not exist.
jom: D:\LocalGit\Repos\Esri\build-DSA-Desktop_Qt_5_15_1_MSVC2019_64bit-Release\arcgis-runtime-toolkit-qt\Plugin\CppApi\Makefile.ArcGISRuntimeToolkit_StaticLib [release] Error 2
jom: D:\LocalGit\Repos\Esri\build-DSA-Desktop_Qt_5_15_1_MSVC2019_64bit-Release\Makefile [sub-D--LocalGit-Repos-Esri-dynamic-situational-awareness-qt-arcgis-runtime-toolkit-qt-Plugin-CppApi-ArcGISRuntimeToolkit_StaticLib-pro-make_first-ordered] Error 2
22:52:43: The process "C:\bin\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project DSA (kit: Desktop Qt 5.15.1 MSVC2019 64bit)
When executing step "Make"
22:52:43: Elapsed time: 00:00.`

**Comment by JamesMBallard** [comment]
@gisfromscratch I setup a local build on Windows and it is working for me. Here is my configuration:

 * Qt 5.15.1
 * ArcGIS Runtime SDK for Qt 100.9
 * Toolkit branch on master.
 * DSA branch on **main** (not master).

Debug:
```
16:47:56: Running steps for project DSA...
16:47:56: Configuration unchanged, skipping qmake step.
16:47:56: Starting: "C:\qt\qtcreator-4.13.2\bin\jom.exe" 
	cd ..\..\sdk\toolkit\Plugin\CppApi\ && ( if not exist Makefile.ArcGISRuntimeToolkit_StaticLib C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile.ArcGISRuntimeToolkit_StaticLib C:\applications\qt\sdk\toolkit\Plugin\CppApi\ArcGISRuntimeToolkit_StaticLib.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib.Debug
	cd Handheld\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\Handheld\Handheld.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Debug
	cd Vehicle\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\Vehicle\Vehicle.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Debug
	cd MessageSimulator\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\MessageSimulator\MessageSimulator.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Debug
16:47:57: The process "C:\qt\qtcreator-4.13.2\bin\jom.exe" exited normally.
16:47:57: Elapsed time: 00:01.
```

Release
```

16:49:19: Running steps for project DSA...
16:49:19: Configuration unchanged, skipping qmake step.
16:49:19: Starting: "C:\qt\qtcreator-4.13.2\bin\jom.exe" 
	cd ..\..\sdk\toolkit\Plugin\CppApi\ && ( if not exist Makefile.ArcGISRuntimeToolkit_StaticLib C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile.ArcGISRuntimeToolkit_StaticLib C:\applications\qt\sdk\toolkit\Plugin\CppApi\ArcGISRuntimeToolkit_StaticLib.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.ArcGISRuntimeToolkit_StaticLib.Release
	cd Handheld\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\Handheld\Handheld.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Release
	cd Vehicle\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\Vehicle\Vehicle.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Release
	cd MessageSimulator\ && ( if not exist Makefile C:\qt\Qt5.15.1\5.15.1\msvc2019_64\bin\qmake.exe -o Makefile C:\applications\qt\example-apps\dynamic-situational-awareness-qt\MessageSimulator\MessageSimulator.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile
	C:\qt\qtcreator-4.13.2\bin\jom.exe -f Makefile.Release
16:49:21: The process "C:\qt\qtcreator-4.13.2\bin\jom.exe" exited normally.
16:49:21: Elapsed time: 00:02.
```

Can you confirm if you've deleted your shadow build folders? I would be sure to try that. If that doesn't work, I would consider recloning the two repos (DSA and toolkit) and reconfiguring the project.

Double check that your DSA branch is on main and not master as well. We have removed the master branch in this repo previously and the default branch is now called "main". I you have previously cloned this repo and are working against the master brach, you will need to switch the branch manually.

**Comment by gisfromscratch** [comment]
Repositories are up-tp-date on main and master. I just cloned both repos two weeks ago, let me try to reproduce this on a clean machine.

From https://github.com/gisfromscratch/dynamic-situational-awareness-qt
`= [up to date]      main       -> origin/main`

From https://github.com/Esri/arcgis-runtime-toolkit-qt
`= [up to date]      master                  -> origin/master`

**Comment by gisfromscratch** [comment]
This seems to be a shadow build or path issue. I was able to build all configurations on a clean machine. On the failing machine deleting the shadow build directories did not solve this issue. I just specified another build directory for the release configuration having a shorter path. Debug and release configuration differed by only 1 char length. At least now it works for all configurations. Thanks for narrowing it down.
